services:
  - type: web
    name: ml-service
    env: python
    rootDir: ml-service
    pythonVersion: 3.10.12
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 5001

